## Upsampling

In [1]:
import numpy as np
import pandas as pd

In [2]:
## Set the random seed for reproducibility
np.random.seed(123)

In [3]:
## Create a dataFrame with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [4]:
n_class_0, n_class_1

(900, 100)

In [5]:
## Create my DataFrame with imbalanced dataset
class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=1, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=1, scale=1, size=n_class_1),
    'target': [1]*n_class_1
})

In [6]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [7]:
df.head()

   feature1  feature2  target
0 -1.085631  0.551302       0
1  0.997345  0.419589       0
2  0.282978  1.815652       0
3 -1.506295 -0.252750       0
4 -0.578600 -0.292004       0

In [8]:
df.tail()

     feature1  feature2  target
995  0.376371  1.845701       1
996  1.239810 -0.119923       1
997  0.131760  0.640703       1
998  1.902006 -0.609695       1
999  1.697490  1.013570       1

In [9]:
df["target"].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [10]:
df[df["target"] == 1]

     feature1  feature2  target
900  0.699768  1.139033       1
901  0.367739  1.025577       1
902  0.795683  0.803557       1
903  1.213696  2.312255       1
904  2.033878  2.187417       1
..        ...       ...     ...
995  0.376371  1.845701       1
996  1.239810 -0.119923       1
997  0.131760  0.640703       1
998  1.902006 -0.609695       1
999  1.697490  1.013570       1

[100 rows x 3 columns]

In [11]:
df_minority = df[df["target"] == 1]
df_majority = df[df["target"] == 0]

In [12]:
! pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (3.6.0)

In [21]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_majority,
                                 replace=True,# Sample with replacement
                                    n_samples=len(df_minority),# To match minority class
                                    random_state = 42 # Reproducible results
)

In [22]:
df_minority_upsampled.head()

     feature1  feature2  target
102  0.712265  0.718151       0
435  1.199988  0.574621       0
860  0.304515 -0.759475       0
270 -1.213385  0.675504       0
106  0.179549 -0.202659       0

In [23]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])
df_upsampled["target"].value_counts()

target
0    1000
Name: count, dtype: int64

## Down Sampling

In [24]:
import numpy as np
import pandas as pd
## Set the random seed for reproducibility
np.random.seed(123)
## Create a dataFrame with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [25]:
n_class_0, n_class_1

(900, 100)

In [ ]:
## Create my DataFrame with imbalanced dataset
class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=1, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=1, scale=1, size=n_class_1),
    'target': [1]*n_class_1
})

df = pd.concat([class_0,class_1]).reset_index(drop=True)
df.head()
df.tail()
df["target"].value_counts()
df[df["target"] == 1]
df_minority = df[df["target"] == 1]
df_majority = df[df["target"] == 0]

In [27]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority,
                                 replace=False, # sample without replacement
                                    n_samples=len(df_minority), # to match minority class
                                    random_state=42 # reproducible results
)
df_majority_downsampled.head()

     feature1  feature2  target
70   0.468439  1.720920       0
827  1.089165 -0.464899       0
231  0.753869 -0.969798       0
588  0.588686 -0.704720       0
39   0.283627  1.012868       0

In [28]:
df_majority_downsampled.shape

(100, 3)

In [31]:
df_majority_downsampled = pd.concat([df_minority, df_majority_downsampled])
df_majority_downsampled = df_majority_downsampled.reset_index(drop=True)
df_majority_downsampled["target"].value_counts()

target
1    300
0    100
Name: count, dtype: int64

DownSampling Is Bad! Because we are loosing data points we can use upsampling