## Label Encoding

In [5]:
import pandas as pd
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Green','Red','Blue']

})
df.head()

   Color
0    Red
1   Blue
2  Green
3  Green
4    Red

In [6]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()
lbl_encoder.fit_transform(df[['Color']])

c:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [7]:
lbl_encoder.transform([['Blue']])
lbl_encoder.transform([['Green']])
lbl_encoder.transform([['Red']])

c:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

## Ordinal Encoding

In [8]:
from sklearn.preprocessing import OrdinalEncoder
## Create a sample DataFrame with an ordinal feature
df = pd.DataFrame({
    'Size': ['Small', 'Medium', 'Large', 'Medium', 'Small']
})

df

     Size
0   Small
1  Medium
2   Large
3  Medium
4   Small

In [11]:
## Create an instance of OrdinalEncoder and then perform fit and transform
encoder = OrdinalEncoder(categories=[['Small', 'Medium', 'Large']])
encoded = encoder.fit_transform(df[['Size']])
encoder.transform([['Medium']])
encoder.transform([['Large']])
encoder.transform([['Small']])

c:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(
c:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(
c:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])