In [1]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
data = [ 1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
## Create a Series From Dictionary
data = {"a":1,"b":2,"c":3,"d":4}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
## Another Format

data = [10,20,30]
index = ["a","b","c"]
pd.Series(data,index = index)

a    10
b    20
c    30
dtype: int64

Data Frame

In [ ]:
## Create a DataFrame from a dictionary of List
data = {
    "Name" : ["Raunak","Rish","Pratap","Harsh"],
    "Age" : [30,35,39,38],
    "City" : ["Praj","Alld","Knpr","Prtp"]
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     name  Age  City
0  Raunak   30  Praj
1    Rish   35  Alld
2  Pratap   39  Knpr
3   Harsh   38  Prtp
<class 'pandas.core.frame.DataFrame'>

In [12]:
import numpy as np
np.array(df)

array([['Raunak', 30, 'Praj'],
       ['Rish', 35, 'Alld'],
       ['Pratap', 39, 'Knpr'],
       ['Harsh', 38, 'Prtp']], dtype=object)

In [94]:
## Create a DataFrame From List Of Dictionaries

data = [
    {"Name" : "Raunak","Age" : 42,"City" : "Praj"},
    {"Name" : "Rish","Age" : 54,"City" : "Alld"},
    {"Name" : "Pratp","Age" : 44,"City" : "Knpr"},
    {"Name" : "Harsh","Age" : 49,"City" : "Prtp"}
]

df = pd.DataFrame(data)
df

# Accessing Data From DataFrame
print(df.loc[0,"Name"])
print(df.iloc[0,1])
print(df.iloc[0,2])
print(df.at[1,"Age"])
print(df.iat[2,1])

## Data Manipulation With Data Frame
df["Salary"] = [500000,600000,700000,300000]
df

## Deleting(Removing) a Column
df.drop("Salary",axis = 1) ## Temprary
df
df.drop("Salary",axis = 1,inplace = True) ## Permanently
df

## Add age to the Column
df["Age"] = df["Age"] + 1 ## Every Age Increase By 1
df

df.drop(0,inplace = True)
df

Raunak
42
Praj
54
44

    Name  Age  City
1   Rish   55  Alld
2  Pratp   45  Knpr
3  Harsh   50  Prtp

In [99]:
## Reading CSV
df = pd.read_csv("sales_data.csv")
df.head(5)
df.tail(5)
df.describe()

,OrderID,Year,Quantity,Price,Sales,Profit
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.00000
mean,1025.50000,2020.700000,3.280000,28834.000000,69288.000000,11070.00000
std,14.57738,3.163891,1.578426,21760.445392,33552.928885,5174.67341
min,1001.00000,2016.000000,1.000000,4500.000000,21200.000000,4000.00000
25%,1013.25000,2018.000000,2.000000,15000.000000,36450.000000,6250.00000
50%,1025.50000,2020.500000,3.000000,21500.000000,64000.000000,10500.00000
75%,1037.75000,2023.000000,4.000000,31000.000000,92750.000000,14750.00000
max,1050.00000,2026.000000,7.000000,72000.000000,132000.000000,23000.00000