In [1]:
## Dataset(Tips Dataset)
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [4]:
df['sex'].value_counts()
df['smoker'].value_counts()
df['day'].value_counts()
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [5]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [29]:
## Feature Encodeing [[Abel Encoding And One Hot Encodeing]]
## Independent and department features
X = df[['tip', 'sex', 'smoker', 'time', 'size']]
y = df['total_bill']

In [30]:
## train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=10)
X_train.head()

      tip   sex smoker    time  size
58   1.76  Male    Yes  Dinner     2
1    1.66  Male     No  Dinner     3
2    3.50  Male     No  Dinner     3
68   2.01  Male     No  Dinner     2
184  3.00  Male    Yes  Dinner     2

In [31]:
## Feature Encoding(label and Ohe Encodeing)
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [32]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

In [33]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

In [34]:
X_test.head()

      tip  sex  smoker  time  size
162  2.00    0       0     0     3
60   3.21    1       1     0     2
61   2.00    1       1     0     2
63   3.76    1       1     0     4
69   2.09    1       1     0     2

In [35]:
## Onehot encoding---- Column Transformr
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')

In [36]:
ct.fit_transform(X_train)

array([[ 0.  ,  1.76,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.66,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  2.01,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  4.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  5.2 ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  4.  ,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  5.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.75,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  3.12,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  5.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  3.39,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  2.3 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.03,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.64,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.17,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.34,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  2.52,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  3.14,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.47,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  3.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  1.61,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  3.5 ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  3.5 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.32,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  4.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  3.18,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  2.75,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  5.14,  0.  ,  0.  ,  5.  ],
       [ 0.  ,  3.07,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.25,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  2.56,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  2.05,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  4.19,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  2.83,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  4.73,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  2.74,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  1.  ],
       [ 0.  ,  2.47,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  5.15,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  2.23,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.31,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  5.92,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  2.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  3.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  2.23,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  2.88,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  2.18,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  4.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  3.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  2.54,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  3.4 ,  1.  ,  0.  ,  2.  ],
       [ 0.  , 10.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.56,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  3.71,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  4.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  2.6 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  3.02,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  1.83,  0.  ,  0.  ,  1.  ],
       [ 1.  ,  2.03,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  3.31,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  7.58,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  3.48,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.5 ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  3.06,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  2.71,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.44,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.57,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  4.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  5.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.5 ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  5.17,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  3.25,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  5.  ,  0.  ,  0.  ,  6.  ],
       [ 0.  ,  2.24,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  6.5 ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  4.08,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  3.27,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  3.76,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  4.5 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  9.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  3.68,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  3.61,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  5.6 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.25,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  4.3 ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  1.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.  ,  1.  ,  1.  ,  5.  ],
       [ 0.  ,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  3.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  1.8 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  2.02,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.2 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  3.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  3.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  4.3 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  3.5 ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.5 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  3.15,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  3.5 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.61,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.45,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  6.7 ,  1.  ,  0.  ,  6.  ],
       [ 1.  ,  1.48,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  5.  ,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  4.  ,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  1.92,  1.  ,  1.  ,  1.  ],
       [ 0.  ,  3.55,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  3.41,  1.  ,  1.  ,  3.  ],
       [ 1.  ,  1.58,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  4.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  2.45,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.98,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  4.29,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  5.85,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  4.34,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  2.75,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.67,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  3.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  3.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  2.24,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.01,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  5.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.96,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  4.67,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  3.75,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  3.48,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.5 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  5.  ,  1.  ,  0.  ,  6.  ],
       [ 1.  ,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.55,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.64,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  3.92,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  2.72,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  4.2 ,  0.  ,  0.  ,  6.  ],
       [ 0.  ,  3.23,  1.  ,  0.  ,  2.  ]])

In [37]:
import sys 
import numpy 
numpy.set_printoptions (threshold=sys.maxsize)
X_test = ct.fit_transform(X_test)
X_test

array([[0.  , 2.  , 0.  , 0.  , 3.  ],
       [0.  , 3.21, 1.  , 1.  , 2.  ],
       [0.  , 2.  , 1.  , 1.  , 2.  ],
       [0.  , 3.76, 1.  , 1.  , 4.  ],
       [0.  , 2.09, 1.  , 1.  , 2.  ],
       [1.  , 5.  , 1.  , 1.  , 2.  ],
       [0.  , 3.51, 1.  , 0.  , 2.  ],
       [0.  , 5.16, 1.  , 1.  , 4.  ],
       [0.  , 5.  , 1.  , 0.  , 2.  ],
       [0.  , 3.6 , 1.  , 0.  , 3.  ],
       [0.  , 5.65, 1.  , 1.  , 2.  ],
       [0.  , 2.5 , 0.  , 1.  , 3.  ],
       [1.  , 1.44, 1.  , 0.  , 2.  ],
       [0.  , 3.09, 0.  , 1.  , 4.  ],
       [0.  , 2.  , 1.  , 0.  , 4.  ],
       [1.  , 1.36, 0.  , 0.  , 3.  ],
       [1.  , 2.  , 0.  , 0.  , 2.  ],
       [1.  , 1.68, 0.  , 0.  , 2.  ],
       [0.  , 3.5 , 0.  , 1.  , 3.  ],
       [0.  , 3.16, 1.  , 1.  , 2.  ],
       [0.  , 1.71, 1.  , 0.  , 2.  ],
       [0.  , 2.5 , 0.  , 1.  , 2.  ],
       [0.  , 2.  , 1.  , 0.  , 2.  ],
       [1.  , 1.63, 0.  , 0.  , 2.  ],
       [0.  , 5.  , 1.  , 0.  , 5.  ],
       [1.  , 2.  , 0.  , 0.  , 2.  ],
       [0.  , 3.08, 1.  , 1.  , 2.  ],
       [1.  , 2.92, 0.  , 0.  , 4.  ],
       [1.  , 2.31, 1.  , 0.  , 2.  ],
       [0.  , 6.73, 1.  , 0.  , 4.  ],
       [0.  , 5.07, 1.  , 0.  , 4.  ],
       [0.  , 6.5 , 0.  , 1.  , 3.  ],
       [0.  , 2.  , 1.  , 0.  , 2.  ],
       [0.  , 2.5 , 1.  , 0.  , 2.  ],
       [0.  , 3.18, 1.  , 0.  , 2.  ],
       [0.  , 1.1 , 0.  , 1.  , 2.  ],
       [0.  , 3.35, 1.  , 0.  , 3.  ],
       [1.  , 2.2 , 1.  , 1.  , 2.  ],
       [0.  , 4.06, 1.  , 1.  , 2.  ],
       [0.  , 3.  , 1.  , 1.  , 4.  ],
       [1.  , 3.  , 1.  , 1.  , 2.  ],
       [0.  , 3.5 , 1.  , 1.  , 3.  ],
       [1.  , 1.5 , 0.  , 0.  , 2.  ],
       [0.  , 3.  , 1.  , 1.  , 5.  ],
       [1.  , 2.  , 0.  , 1.  , 2.  ],
       [0.  , 1.97, 1.  , 0.  , 2.  ],
       [0.  , 3.5 , 1.  , 0.  , 2.  ],
       [0.  , 2.  , 1.  , 0.  , 2.  ],
       [1.  , 1.73, 1.  , 0.  , 2.  ],
       [0.  , 3.48, 0.  , 1.  , 2.  ],
       [0.  , 4.08, 1.  , 0.  , 2.  ],
       [0.  , 6.  , 1.  , 0.  , 4.  ],
       [1.  , 3.23, 0.  , 1.  , 3.  ],
       [0.  , 4.71, 1.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  ],
       [0.  , 3.  , 1.  , 1.  , 2.  ],
       [1.  , 2.01, 0.  , 1.  , 2.  ],
       [1.  , 2.  , 1.  , 0.  , 2.  ],
       [0.  , 3.11, 1.  , 1.  , 2.  ],
       [1.  , 2.  , 0.  , 1.  , 2.  ],
       [0.  , 3.  , 1.  , 0.  , 2.  ]])

In [38]:
## SVR---Support Vector Regression 
from sklearn.svm import SVR
svr = SVR()
svr.fit(X_train,y_train)
y_pred = svr.predict(X_test)

c:\Users\gp298\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

In [39]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.304361816840079
5.014241696921823

In [40]:
## Hyper Parameter Tuining using GridSearchCV
from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001],'kernel':['rbf']}
grid = GridSearchCV(SVR(),param_grid,refit=True,verbose=3)

In [41]:
## fitting the model from grid search 
grid.fit(X_train,y_train)
grid.best_params_
grid_prediction = grid.predict(X_test)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.060 total time=   0.1s
[CV 2/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.048 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.126 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.049 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.079 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.017 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.028 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.007 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.132 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.061 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.053 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.027 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.108 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.040 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.058 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.080 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.068 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.167 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.006 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.105 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.073 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.173 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.013 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.110 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.122 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.122 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.188 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.203 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.163 total time=   0.0s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.198 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.263 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.544 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.352 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.512 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.119 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.221 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.272 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.308 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.251 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.014 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.096 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.049 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.051 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.080 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.068 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.167 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.006 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.105 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.319 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.333 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.546 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.150 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.446 total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.169 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.441 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.716 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.428 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.563 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.211 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.486 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.704 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.443 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.594 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.140 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.275 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.335 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.341 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.278 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.0001, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END ...C=10, gamma=0.0001, kernel=rbf;, score=-0.013 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.0001, kernel=rbf;, score=-0.094 total time=   0.0s
[CV 4/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.050 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.0001, kernel=rbf;, score=-0.051 total time=   0.0s
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.316 total time=   0.0s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.188 total time=   0.0s
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.536 total time=   0.0s
[CV 4/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.253 total time=   0.0s
[CV 5/5] END ........C=100, gamma=1, kernel=rbf;, score=0.401 total time=   0.0s
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.115 total time=   0.0s
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.568 total time=   0.0s
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.687 total time=   0.0s
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.382 total time=   0.0s
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.466 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.190 total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.535 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.733 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.420 total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.584 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.212 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.519 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.723 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.431 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.602 total time=   0.0s
[CV 1/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.142 total time=   0.0s
[CV 2/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.285 total time=   0.0s
[CV 3/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.342 total time=   0.0s
[CV 4/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.345 total time=   0.0s
[CV 5/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.284 total time=   0.0s
[CV 1/5] END ......C=1000, gamma=1, kernel=rbf;, score=-0.292 total time=   0.0s
[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.116 total time=   0.0s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.340 total time=   0.0s
[CV 4/5] END ......C=1000, gamma=1, kernel=rbf;, score=-1.341 total time=   0.0s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.349 total time=   0.0s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.252 total time=   0.0s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.487 total time=   0.0s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.331 total time=   0.0s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.033 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.484 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.130 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.593 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.738 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.434 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.535 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.221 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.554 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.729 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.395 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.628 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.213 total time=   0.0s
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.521 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.723 total time=   0.0s
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.430 total time=   0.0s
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.602 total time=   0.0s

c:\Users\gp298\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

In [42]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,grid_prediction))
print(mean_absolute_error(y_test,grid_prediction))

-0.2488120263260345
7.481389558709017